# Generated by Django 5.2.4 on 2025-07-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobRecordd",
            new_name="JobRecord",
        ),
    ]
