# Generated by Django 5.2.4 on 2025-07-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_rename_jobrecordd_jobrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="jobrecord",
            unique_together={("job_title", "work_year", "employee_residence")},
        ),
    ]
