# Generated by Django 5.2.4 on 2025-07-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_jobrecord_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="jobrecord",
            unique_together={("job_title", "work_year", "employee_residence")},
        ),
    ]
